#smfigap input file 

# Input File scheme
file_scheme = 1

# Basic setting
rounds = 8
iterations = 2
repeat_pairings = true

[[fields]]
	type = "Funino"
	subtype="Vorne"
	name="1"
[[fields]]
	type = "Jugendtore"
	subtype="Vorne"
	name="2"
[[fields]]
	type = "Funino"
	subtype="Vorne"
	name="3"
[[fields]]
	type = "Jugendtore"
	subtype="Vorne"
	name="4"
[[fields]]
	type = "Funino"
	subtype="Hinten"
	name="5"
[[fields]]
	type = "Jugendtore"
	subtype="Hinten"
	name="6"
[[fields]]
	type = "Funino"
	subtype="Hinten"
	name="7"
[[fields]]
	type = "Jugendtore"
	subtype="Hinten"
	name="8"

[[clubs]]
	name = "A"
	colors = [ '1', '2'] 
[[clubs]]
	name = "B"
	colors = [ '1', '2'] 
[[clubs]]
	name = "C"
	colors = [ '1', '2'] 
[[clubs]]
	name = "D"
	colors = [ '1', '2']
[[clubs]]
	name = "E"
	colors = [ '1', '2'] 
[[clubs]]
	name = "F"
	colors = [ '1', '2'] 
[[clubs]]
	name = "G"
	colors = [ '1', '2'] 
[[clubs]]
	name = "H"
	colors = [ '1', '2']   

[conditions]
	[conditions.pause_games]
		max = 3
	[[conditions.field_types]]
		name = "Funino"
		min = 4
		max = 4
	[[conditions.field_types]]
		name = "Jugendtore"
		min = 4
		max = 4
	[conditions.same_club]
		max = 0
[[conditions.subtypes]]
  name = "Vorne" 
  teams_deny = ['A', '2', 'B', '2', 'C', '2', 'D', '2', 'E', '2', 'F', '2', 'G', '2', 'H', '2'] 
[[conditions.subtypes]]
  name = "Hinten" 
  teams_deny = ['A', '1', 'B', '1', 'C', '1', 'D', '1', 'E', '1', 'F', '1', 'G', '1', 'H', '1']

# Output section
# her in seperate format.toml file (-f option)           