# smfigap input file. This is a toml File, see https://github.com/toml-lang/toml for details of the Toml specification
# There are  two sections of the configuration, the Gameplan section where fields, teams, and conditions are defined
# and the Output section, where additional information and format information for the output file are defined.

# Gameplan section

# Input File scheme ( Not used yet)
file_scheme = 1

# Number of Rounds to play (Range: 1-10)
rounds = 6

# Fields (Range: 1-10)
# Fields are ordered in the order of definition.
# For every field there are three fields:
# - type: This is used for the fieldtype conditions, and for the output file
# - subtype: Used to restrict certain teams to certain subtypes. Can be used two divide the tournamen in subtournaments, but is not restricted to that.
# - name: The name of the filed used in the Output File
   
[[fields]]
    type = "Small Goals"
    subtype="Left"
    name="1"
[[fields]]
    type = "Large Goals"
    subtype="Left"
    name="2"
[[fields]]
    type = "Small Goals"
    subtype="Right"
    name="3"
[[fields]]
    type = "Large Goals"
    subtype="Right"
    name="4"

# Clubs (Range: 1-16)
# Clubs are ordered in the order of definition.
# For every field there are two fields:
# - name: This is used for the same_club condition and for the output file
# - colors: Defines the Teams within a Club. Typically these are colors corresponing to the trikot color, but theres no restriction to colors

[[clubs]]
    name = "North"
    colors = [ 'Red', 'Green'] 
[[clubs]]
    name = "South"
    colors = [ 'Red', 'Blue'] 
[[clubs]]
    name = "West"
    colors = [ 'Red', 'Green'] 
[[clubs]]
    name = "East"
    colors = [ 'Red'] 
    
# Conditions

[conditions]
    [conditions.pause_games]
        max = 1
    [[conditions.field_types]]
        name = "Small Goals"
        min = 2
        max = 3
    [[conditions.field_types]]
        name = "Large Goals"
        min = 2
        max = 3
    [conditions.same_club]
        max = 2
    [conditions.empty_fields]
        max = 1

# Output section
# her in seperate format.toml file (-f option)      
